name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"
      - name: List files
        run: ls -la

