name: Hello
on:
  push:
    branches: [ main ]
jobs:
  my-hello-job:
    runs-on: ubuntu-22.04
    steps:
    - name: Say hello
      run: echo "Hello dear class"
    - name: Show data
      run: date
    - name: List files
      run: ls -la